---
- hosts: group1

  tasks:

  - name: installing httpd

    yum:

      name: httpd
      state: present

  - name: starting the service

    service: name=httpd state=started

  - name: copying the file

    copy:
      src: /tmp/index.html
      dest: /var/www/html/index.html


