---
- hosts: group1

  tasks:
  - name: Install Java - java-1.8.0-openjdk
    yum:
      name: java-1.8.0-openjdk
      state: present
  - name: Create Linux user-gruop(jboss) for Jboss admin user (jboss)
    group:
      name: jboss
      state: present
  - name: Create Linux user for Jboss admin user (jboss)
    user:
      name: jboss
      group: jboss
      state: present
  - name: download  Jboss server 7.1.1.1
    get_url:
      url: http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.zip
      dest: /tmp
      mode: 0777
#  - name: test copy jboss-as-7.1.1.Final.zip
#    copy:
#      src: /home/demo_user/a
#      dest: /home/demo_user/b
  - name: unarchive / unzip the Jboss zip file
    unarchive:
      src: /tmp/jboss-as-7.1.1.Final.zip
      dest: /usr/share
      owner: jboss
      remote_src: yes


